# -*- coding: utf-8 -*-
"""Sync V1 radar indicator catalog into DuckDB.

Targets 40-60 high-value indicators across:
  - China macro (money supply, credit, inflation, production, investment)
  - Global market (rates, FX, commodities, volatility)
  - Sentiment / positioning
  - Sector & cross-asset

Status legend:
  active   – collectable now via akshare / yfinance / existing scripts
  planned  – valuable but needs a new data source or API access
  disabled – unreliable, deprecated, or duplicates another indicator

Run:
    python scripts/sync_radar_catalog.py
"""
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.services.radar_store import RadarStore

# ---------------------------------------------------------------------------
# V1 Indicator catalog definition
# ---------------------------------------------------------------------------

CATALOG_V1: list[dict] = [
    # ===== China: Money & Credit =====
    {
        "indicator_code": "CN_M1_YOY",
        "category": "macro_cn",
        "indicator_type": "money_supply",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 90,
        "affected_assets": ["A_shares", "CNY", "CN_bonds"],
        "affected_sectors": ["banking", "real_estate"],
        "source": "akshare:macro_china_money_supply",
        "confidence": 0.95,
        "status": "active",
        "notes": "M1 同比增速，社融先行指标",
    },
    {
        "indicator_code": "CN_M2_YOY",
        "category": "macro_cn",
        "indicator_type": "money_supply",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 90,
        "affected_assets": ["A_shares", "CNY", "CN_bonds"],
        "affected_sectors": ["banking", "real_estate"],
        "source": "akshare:macro_china_money_supply",
        "confidence": 0.95,
        "status": "active",
        "notes": "M2 同比增速，衡量广义流动性",
    },
    {
        "indicator_code": "CN_M1M2_SCIS",
        "category": "macro_cn",
        "indicator_type": "derived",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 60,
        "affected_assets": ["A_shares"],
        "affected_sectors": ["broad_market"],
        "source": "derived",
        "confidence": 0.85,
        "status": "active",
        "notes": "M1-M2 剪刀差，反映资金活化程度",
    },
    {
        "indicator_code": "CN_TSF_YOY",
        "category": "macro_cn",
        "indicator_type": "credit",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 90,
        "affected_assets": ["A_shares", "CN_bonds"],
        "affected_sectors": ["banking", "infrastructure"],
        "source": "akshare:macro_china_social_financing",
        "confidence": 0.9,
        "status": "active",
        "notes": "社融存量同比",
    },
    {
        "indicator_code": "CN_NEW_LOANS",
        "category": "macro_cn",
        "indicator_type": "credit",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 90,
        "affected_assets": ["A_shares", "CN_bonds"],
        "affected_sectors": ["banking"],
        "source": "akshare:macro_china_new_financial_credit",
        "confidence": 0.9,
        "status": "active",
        "notes": "当月新增人民币贷款",
    },

    # ===== China: Inflation =====
    {
        "indicator_code": "CN_CPI_YOY",
        "category": "macro_cn",
        "indicator_type": "inflation",
        "frequency": "monthly",
        "direction": "coincident",
        "half_life_days": 120,
        "affected_assets": ["CN_bonds", "CNY"],
        "affected_sectors": ["consumer", "agriculture"],
        "source": "akshare:macro_china_cpi",
        "confidence": 0.95,
        "status": "active",
        "notes": "CPI 同比",
    },
    {
        "indicator_code": "CN_PPI_YOY",
        "category": "macro_cn",
        "indicator_type": "inflation",
        "frequency": "monthly",
        "direction": "coincident",
        "half_life_days": 120,
        "affected_assets": ["A_shares", "CN_bonds"],
        "affected_sectors": ["materials", "energy", "industrials"],
        "source": "akshare:macro_china_ppi",
        "confidence": 0.95,
        "status": "active",
        "notes": "PPI 同比",
    },
    {
        "indicator_code": "CN_CPI_PPI_SCIS",
        "category": "macro_cn",
        "indicator_type": "derived",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 90,
        "affected_assets": ["A_shares"],
        "affected_sectors": ["materials", "consumer"],
        "source": "derived",
        "confidence": 0.8,
        "status": "active",
        "notes": "CPI-PPI 剪刀差，上下游利润分配",
    },

    # ===== China: Production & Investment =====
    {
        "indicator_code": "CN_INDUSTRIAL_VA_YOY",
        "category": "macro_cn",
        "indicator_type": "production",
        "frequency": "monthly",
        "direction": "coincident",
        "half_life_days": 90,
        "affected_assets": ["A_shares"],
        "affected_sectors": ["industrials", "materials", "energy"],
        "source": "akshare:macro_china_industrial_production_yoy",
        "confidence": 0.9,
        "status": "active",
        "notes": "规模以上工业增加值同比",
    },
    {
        "indicator_code": "CN_FA_YOY",
        "category": "macro_cn",
        "indicator_type": "investment",
        "frequency": "monthly",
        "direction": "coincident",
        "half_life_days": 90,
        "affected_assets": ["A_shares", "CN_bonds"],
        "affected_sectors": ["infrastructure", "materials"],
        "source": "akshare:macro_china_fai",
        "confidence": 0.85,
        "status": "active",
        "notes": "固定资产投资完成额同比",
    },
    {
        "indicator_code": "CN_RE_INVEST_YOY",
        "category": "macro_cn",
        "indicator_type": "investment",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 120,
        "affected_assets": ["A_shares", "CN_bonds"],
        "affected_sectors": ["real_estate", "materials", "banking"],
        "source": "akshare:macro_china_fai_re",
        "confidence": 0.9,
        "status": "active",
        "notes": "房地产开发投资完成额同比",
    },
    {
        "indicator_code": "CN_RE_SALES_YOY",
        "category": "macro_cn",
        "indicator_type": "investment",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 90,
        "affected_assets": ["A_shares"],
        "affected_sectors": ["real_estate"],
        "source": "akshare:macro_china_re_sales",
        "confidence": 0.85,
        "status": "active",
        "notes": "商品房销售面积同比",
    },
    {
        "indicator_code": "CN_RE_SQ_STARTS_YOY",
        "category": "macro_cn",
        "indicator_type": "investment",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 90,
        "affected_assets": ["A_shares"],
        "affected_sectors": ["real_estate", "materials"],
        "source": "akshare:macro_china_re_starts",
        "confidence": 0.8,
        "status": "active",
        "notes": "房屋新开工面积同比",
    },
    {
        "indicator_code": "CN_RETAIL_SALES_YOY",
        "category": "macro_cn",
        "indicator_type": "consumption",
        "frequency": "monthly",
        "direction": "coincident",
        "half_life_days": 90,
        "affected_assets": ["A_shares"],
        "affected_sectors": ["consumer"],
        "source": "akshare:macro_china_retail_sales_yoy",
        "confidence": 0.9,
        "status": "active",
        "notes": "社会消费品零售总额同比",
    },
    {
        "indicator_code": "CN_EXPORT_YOY",
        "category": "macro_cn",
        "indicator_type": "trade",
        "frequency": "monthly",
        "direction": "coincident",
        "half_life_days": 90,
        "affected_assets": ["CNY", "A_shares"],
        "affected_sectors": ["export", "tech", "textiles"],
        "source": "akshare:macro_china_exports_yoy",
        "confidence": 0.9,
        "status": "active",
        "notes": "出口金额同比",
    },
    {
        "indicator_code": "CN_IMPORT_YOY",
        "category": "macro_cn",
        "indicator_type": "trade",
        "frequency": "monthly",
        "direction": "coincident",
        "half_life_days": 90,
        "affected_assets": ["CNY", "A_shares"],
        "affected_sectors": ["commodities", "energy"],
        "source": "akshare:macro_china_imports_yoy",
        "confidence": 0.9,
        "status": "active",
        "notes": "进口金额同比",
    },
    {
        "indicator_code": "CN_TRADE_SURPLUS",
        "category": "macro_cn",
        "indicator_type": "trade",
        "frequency": "monthly",
        "direction": "coincident",
        "half_life_days": 90,
        "affected_assets": ["CNY"],
        "affected_sectors": ["broad_market"],
        "source": "akshare:macro_china_trade_balance",
        "confidence": 0.9,
        "status": "active",
        "notes": "贸易顺差",
    },
    {
        "indicator_code": "CN_FDI_YOY",
        "category": "macro_cn",
        "indicator_type": "investment",
        "frequency": "monthly",
        "direction": "lagging",
        "half_life_days": 180,
        "affected_assets": ["CNY"],
        "affected_sectors": ["broad_market"],
        "source": "akshare:macro_china_fdi",
        "confidence": 0.75,
        "status": "planned",
        "notes": "外商直接投资同比，akshare 字段可能不完整，待验证",
    },

    # ===== China: PMI =====
    {
        "indicator_code": "CN_PMI_MFG",
        "category": "macro_cn",
        "indicator_type": "sentiment",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 60,
        "affected_assets": ["A_shares"],
        "affected_sectors": ["industrials", "materials"],
        "source": "akshare:macro_china_pmi",
        "confidence": 0.95,
        "status": "active",
        "notes": "制造业PMI",
    },
    {
        "indicator_code": "CN_PMI_NONMFG",
        "category": "macro_cn",
        "indicator_type": "sentiment",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 60,
        "affected_assets": ["A_shares"],
        "affected_sectors": ["services", "consumer"],
        "source": "akshare:macro_china_non_pmi",
        "confidence": 0.9,
        "status": "active",
        "notes": "非制造业PMI",
    },

    # ===== China: Rates & Liquidity =====
    {
        "indicator_code": "CN_DR007",
        "category": "macro_cn",
        "indicator_type": "rate",
        "frequency": "daily",
        "direction": "coincident",
        "half_life_days": 30,
        "affected_assets": ["CN_bonds", "A_shares"],
        "affected_sectors": ["banking"],
        "source": "akshare:interbank_rates",
        "confidence": 0.95,
        "status": "active",
        "notes": "银行间存款类金融机构7天回购利率",
    },
    {
        "indicator_code": "CN_SHIBOR_1W",
        "category": "macro_cn",
        "indicator_type": "rate",
        "frequency": "daily",
        "direction": "coincident",
        "half_life_days": 14,
        "affected_assets": ["CN_bonds", "A_shares"],
        "affected_sectors": ["banking"],
        "source": "akshare:shibor",
        "confidence": 0.95,
        "status": "active",
        "notes": "SHIBOR 1周",
    },
    {
        "indicator_code": "CN_LPR_1Y",
        "category": "macro_cn",
        "indicator_type": "rate",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 180,
        "affected_assets": ["CN_bonds", "A_shares"],
        "affected_sectors": ["real_estate", "banking"],
        "source": "akshare:macro_china_lpr",
        "confidence": 0.95,
        "status": "active",
        "notes": "LPR 1年期",
    },
    {
        "indicator_code": "CN_LPR_5Y",
        "category": "macro_cn",
        "indicator_type": "rate",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 180,
        "affected_assets": ["CN_bonds", "A_shares"],
        "affected_sectors": ["real_estate", "banking"],
        "source": "akshare:macro_china_lpr",
        "confidence": 0.95,
        "status": "active",
        "notes": "LPR 5年期",
    },
    {
        "indicator_code": "CN_10Y_YIELD",
        "category": "macro_cn",
        "indicator_type": "rate",
        "frequency": "daily",
        "direction": "coincident",
        "half_life_days": 30,
        "affected_assets": ["CN_bonds", "A_shares"],
        "affected_sectors": ["banking"],
        "source": "akshare:bond_spot",
        "confidence": 0.9,
        "status": "planned",
        "notes": "中国10年期国债收益率，待确认akshare可用接口",
    },

    # ===== Global: Rates & Yield Curve =====
    {
        "indicator_code": "US_2Y_YIELD",
        "category": "global_macro",
        "indicator_type": "rate",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 30,
        "affected_assets": ["US_equities", "USD", "EM_assets"],
        "affected_sectors": ["global_banking"],
        "source": "yfinance:^IRX or stooq",
        "confidence": 0.95,
        "status": "active",
        "notes": "美国2年期国债收益率",
    },
    {
        "indicator_code": "US_10Y_YIELD",
        "category": "global_macro",
        "indicator_type": "rate",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 30,
        "affected_assets": ["US_equities", "USD", "EM_assets", "A_shares"],
        "affected_sectors": ["global_banking", "tech"],
        "source": "yfinance:^TNX",
        "confidence": 0.95,
        "status": "active",
        "notes": "美国10年期国债收益率，全球资产定价锚",
    },
    {
        "indicator_code": "US_2S10S",
        "category": "global_macro",
        "indicator_type": "derived",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 60,
        "affected_assets": ["US_equities", "USD", "global_bonds"],
        "affected_sectors": ["global_banking"],
        "source": "derived",
        "confidence": 0.9,
        "status": "active",
        "notes": "2s10s 利差，衰退预警指标",
    },

    # ===== Global: FX & Commodities =====
    {
        "indicator_code": "DXY",
        "category": "global_macro",
        "indicator_type": "index",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 30,
        "affected_assets": ["EM_assets", "gold", "CNY"],
        "affected_sectors": ["export", "commodities"],
        "source": "yfinance:DX-Y.NYB",
        "confidence": 0.9,
        "status": "active",
        "notes": "美元指数",
    },
    {
        "indicator_code": "GOLD",
        "category": "global_macro",
        "indicator_type": "commodity",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 30,
        "affected_assets": ["gold", "gold_miners", "USD"],
        "affected_sectors": ["materials"],
        "source": "yfinance:GC=F",
        "confidence": 0.95,
        "status": "active",
        "notes": "COMEX 黄金期货",
    },
    {
        "indicator_code": "USD_CNH",
        "category": "global_macro",
        "indicator_type": "fx",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 14,
        "affected_assets": ["A_shares", "HK_equities", "CNY"],
        "affected_sectors": ["export", "import"],
        "source": "yfinance:USDCNH=X or akshare",
        "confidence": 0.95,
        "status": "active",
        "notes": "美元兑离岸人民币",
    },
    {
        "indicator_code": "COPPER",
        "category": "global_macro",
        "indicator_type": "commodity",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 30,
        "affected_assets": ["A_shares", "EM_assets"],
        "affected_sectors": ["materials", "industrials"],
        "source": "yfinance:HG=F",
        "confidence": 0.9,
        "status": "active",
        "notes": "COMEX 铜期货，铜金比为经济周期指标",
    },
    {
        "indicator_code": "COPPER_GOLD_RATIO",
        "category": "global_macro",
        "indicator_type": "derived",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 60,
        "affected_assets": ["A_shares", "global_equities"],
        "affected_sectors": ["broad_market"],
        "source": "derived",
        "confidence": 0.85,
        "status": "active",
        "notes": "铜金比，经济增长预期代理变量",
    },
    {
        "indicator_code": "CRUDE_OIL",
        "category": "global_macro",
        "indicator_type": "commodity",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 30,
        "affected_assets": ["energy_stocks", "USD", "CNY"],
        "affected_sectors": ["energy", "transportation"],
        "source": "yfinance:CL=F",
        "confidence": 0.95,
        "status": "active",
        "notes": "WTI 原油期货",
    },

    # ===== Global: Volatility & Sentiment =====
    {
        "indicator_code": "VIX",
        "category": "global_macro",
        "indicator_type": "volatility",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 14,
        "affected_assets": ["global_equities", "US_equities", "A_shares"],
        "affected_sectors": ["broad_market"],
        "source": "yfinance:^VIX",
        "confidence": 0.95,
        "status": "active",
        "notes": "CBOE 波动率指数，恐慌指标",
    },
    {
        "indicator_code": "CNN_FEAR_GREED",
        "category": "sentiment",
        "indicator_type": "sentiment",
        "frequency": "daily",
        "direction": "contrarian",
        "half_life_days": 7,
        "affected_assets": ["US_equities"],
        "affected_sectors": ["broad_market"],
        "source": "CNN Fear & Greed Index",
        "confidence": 0.7,
        "status": "planned",
        "notes": "CNN 恐惧贪婪指数，需网页抓取，待验证稳定性",
    },
    {
        "indicator_code": "US_AAII_BULL",
        "category": "sentiment",
        "indicator_type": "sentiment",
        "frequency": "weekly",
        "direction": "contrarian",
        "half_life_days": 14,
        "affected_assets": ["US_equities"],
        "affected_sectors": ["broad_market"],
        "source": "AAII",
        "confidence": 0.75,
        "status": "planned",
        "notes": "AAII 投资者情绪调查，需从 AAII 网站抓取",
    },

    # ===== Global: Equity & Flows =====
    {
        "indicator_code": "US_HY_SPREAD",
        "category": "global_macro",
        "indicator_type": "credit_spread",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 30,
        "affected_assets": ["US_equities", "global_bonds"],
        "affected_sectors": ["banking", "high_yield"],
        "source": "FRED:ICE BofA HY OAS",
        "confidence": 0.8,
        "status": "planned",
        "notes": "高收益债利差，信用风险代理，可通过 FRED API 获取",
    },
    {
        "indicator_code": "CN_NORTH_FLOW",
        "category": "flow",
        "indicator_type": "capital_flow",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 14,
        "affected_assets": ["A_shares", "HK_equities"],
        "affected_sectors": ["broad_market"],
        "source": "akshare:stock_hsgt_north_net_flow_in",
        "confidence": 0.95,
        "status": "active",
        "notes": "北向资金净流入，已有 sync_north_money.py",
    },
    {
        "indicator_code": "CN_SOUTH_FLOW",
        "category": "flow",
        "indicator_type": "capital_flow",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 14,
        "affected_assets": ["HK_equities"],
        "affected_sectors": ["broad_market"],
        "source": "akshare:stock_hsgt_south_net_flow_in",
        "confidence": 0.95,
        "status": "active",
        "notes": "南向资金净流入，已有 sync_south_flow.py",
    },
    {
        "indicator_code": "CN_MARGIN_DEBT",
        "category": "flow",
        "indicator_type": "leverage",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 14,
        "affected_assets": ["A_shares"],
        "affected_sectors": ["brokerage", "broad_market"],
        "source": "akshare:margin_debt",
        "confidence": 0.85,
        "status": "planned",
        "notes": "A 股融资融券余额，akshare 可能有接口",
    },

    # ===== Sector & Cross-Asset =====
    {
        "indicator_code": "CN_SECTOR_TECH_INDEX",
        "category": "sector",
        "indicator_type": "index",
        "frequency": "daily",
        "direction": "coincident",
        "half_life_days": 30,
        "affected_assets": ["A_shares"],
        "affected_sectors": ["tech"],
        "source": "akshare:sector_index",
        "confidence": 0.8,
        "status": "planned",
        "notes": "A 股科技行业指数相对收益",
    },
    {
        "indicator_code": "CN_SECTOR_FIN_INDEX",
        "category": "sector",
        "indicator_type": "index",
        "frequency": "daily",
        "direction": "coincident",
        "half_life_days": 30,
        "affected_assets": ["A_shares"],
        "affected_sectors": ["banking"],
        "source": "akshare:sector_index",
        "confidence": 0.8,
        "status": "planned",
        "notes": "A 股金融行业指数相对收益",
    },
    {
        "indicator_code": "CN_SECTOR_RE_INDEX",
        "category": "sector",
        "indicator_type": "index",
        "frequency": "daily",
        "direction": "coincident",
        "half_life_days": 30,
        "affected_assets": ["A_shares"],
        "affected_sectors": ["real_estate"],
        "source": "akshare:sector_index",
        "confidence": 0.8,
        "status": "planned",
        "notes": "A 股地产行业指数相对收益",
    },

    # ===== Macro Composites =====
    {
        "indicator_code": "CN_MACRO_SURPRISE",
        "category": "macro_cn",
        "indicator_type": "composite",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 60,
        "affected_assets": ["A_shares"],
        "affected_sectors": ["broad_market"],
        "source": "derived",
        "confidence": 0.7,
        "status": "planned",
        "notes": "宏观数据惊喜指数（实际值 vs 预期偏差），需市场预期数据源",
    },
    {
        "indicator_code": "CN_CREDIT_IMPULSE",
        "category": "macro_cn",
        "indicator_type": "derived",
        "frequency": "monthly",
        "direction": "leading",
        "half_life_days": 60,
        "affected_assets": ["A_shares", "CN_bonds"],
        "affected_sectors": ["banking", "real_estate"],
        "source": "derived",
        "confidence": 0.85,
        "status": "active",
        "notes": "中国信用脉冲（新增社融 / 名义GDP），已被多项研究验证为A股领先指标",
    },

    # ===== Housing & Property =====
    {
        "indicator_code": "CN_70CITY_HOME_PRICE",
        "category": "macro_cn",
        "indicator_type": "real_estate",
        "frequency": "monthly",
        "direction": "lagging",
        "half_life_days": 180,
        "affected_assets": ["A_shares"],
        "affected_sectors": ["real_estate"],
        "source": "akshare:macro_china_70_city_price",
        "confidence": 0.85,
        "status": "active",
        "notes": "70城房价指数同比",
    },

    # ===== External: Japan =====
    {
        "indicator_code": "JP_CPI_YOY",
        "category": "global_macro",
        "indicator_type": "inflation",
        "frequency": "monthly",
        "direction": "coincident",
        "half_life_days": 90,
        "affected_assets": ["JPY", "JP_equities"],
        "affected_sectors": ["broad_market"],
        "source": "akshare:japan_cpi",
        "confidence": 0.8,
        "status": "planned",
        "notes": "日本CPI同比，关注BOJ政策转向信号",
    },
    {
        "indicator_code": "JP_USDJPY",
        "category": "global_macro",
        "indicator_type": "fx",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 14,
        "affected_assets": ["JPY", "JP_equities", "CNY"],
        "affected_sectors": ["export"],
        "source": "yfinance:JPY=X",
        "confidence": 0.95,
        "status": "active",
        "notes": "美元兑日元，套息交易晴雨表",
    },

    # ===== External: Europe =====
    {
        "indicator_code": "EU_CPI_YOY",
        "category": "global_macro",
        "indicator_type": "inflation",
        "frequency": "monthly",
        "direction": "coincident",
        "half_life_days": 90,
        "affected_assets": ["EUR", "EU_equities"],
        "affected_sectors": ["broad_market"],
        "source": "akshare:eurozone_cpi",
        "confidence": 0.8,
        "status": "planned",
        "notes": "欧元区CPI同比",
    },

    # ===== Emerging Market Proxy =====
    {
        "indicator_code": "EM_FLOWS_EPFR",
        "category": "global_macro",
        "indicator_type": "capital_flow",
        "frequency": "weekly",
        "direction": "leading",
        "half_life_days": 21,
        "affected_assets": ["EM_assets", "A_shares"],
        "affected_sectors": ["broad_market"],
        "source": "EPFR",
        "confidence": 0.6,
        "status": "disabled",
        "notes": "EPFR 新兴市场资金流，需付费订阅，暂不可靠",
    },
    {
        "indicator_code": "USD_INR",
        "category": "global_macro",
        "indicator_type": "fx",
        "frequency": "daily",
        "direction": "leading",
        "half_life_days": 21,
        "affected_assets": ["INR", "EM_assets"],
        "affected_sectors": ["broad_market"],
        "source": "yfinance:INR=X",
        "confidence": 0.7,
        "status": "planned",
        "notes": "美元兑印度卢比，新兴市场情绪代理",
    },
]


def main() -> None:
    started_at = datetime.now(timezone.utc).isoformat()
    print("=" * 60)
    print(f"Radar Catalog Sync – {started_at}")
    print("=" * 60)
    print(f"Total indicators in V1: {len(CATALOG_V1)}")

    store = RadarStore()
    store.ensure_schema()

    # Upsert catalog
    n = store.upsert_indicator_catalog(CATALOG_V1)
    print(f"[OK] Upserted {n} indicator catalog rows")

    # Print status breakdown
    conn = store.get_connection()
    try:
        rows = conn.execute(
            "SELECT status, COUNT(*) FROM indicator_catalog GROUP BY status ORDER BY status"
        ).fetchall()
        print("\nStatus breakdown:")
        for status, count in rows:
            print(f"  {status}: {count}")
    finally:
        conn.close()

    # Record source run
    store.record_source_run(
        source_name="sync_radar_catalog",
        target_table="indicator_catalog",
        started_at=started_at,
        finished_at=datetime.now(timezone.utc).isoformat(),
        status="success",
        rows_read=len(CATALOG_V1),
        rows_upserted=n,
    )

    print("\n[OK] Catalog sync complete.")


if __name__ == "__main__":
    main()
